# This is a basic workflow to help you get started with Actions

name: Build wycode.cn

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
env:
  TZ: 'Asia/Shanghai'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # setup node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with: 
          node-version: '14'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: |
          npm install hexo-cli@4.2.0 -g
          npm ci
          npm run build
#       - run: |
#           tar czvf public.tar.gz public
#           echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m%d.%H%M")" >> $GITHUB_ENV
#       - name: Upload public to Releases
#         uses: softprops/action-gh-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ env.PACKAGED_OUTPUTDATE }}
#           files: |
#             public.tar.gz
      # Deploy
#       - name: rsync uploader
#         uses: Pendect/action-rsyncer@v1.1.0
#         env:
#           DEPLOY_KEY: ${{secrets.SERVER_KEY}}
#         with:
#           flags: '-avzr --delete'
#           options: ''
#           ssh_options: '-p 5190'
#           src: 'public/'
#           dest: 'root@wycode.cn:/root/data/nginx/www/wycode.cn'
          
      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.3.2
        with:
          host: 'wycode.cn'
          port: 5190 # optional, default is 22 
          privateKey: ${{ secrets.SERVER_KEY }} 
          localDir: 'public'
          remoteDir: '/root/data/nginx/www/wycode.cn/'
          dryRun: false # optional
    
      - name: Deploy to Github pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          repo: wangyucode/wangyucode.github.io
          target_branch: master
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.WY_GITHUB_TOKEN }}
          
          
